name: Test Self-Hosted Runner

on:
  workflow_dispatch: # allows manual trigger from GitHub Actions tab

jobs:
  test-job:
    runs-on: self-hosted
    steps:
      - name: Ensure _work directory exists
        run: |
          mkdir -p _work
          echo "_work directory ready"

      - name: Check runner info
        run: |
          echo "Runner is working!"
          echo "Current directory: $(pwd)"
          echo "Date: $(date)"
